# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97bb3841fc59c83eabc1edef62223f0eb2821c5ea3730600a7ae280d38f0ee0fa2b6f3f4b5ff33c26bffd6a0702491abca148131c0855f651f8e419f0fe238b5

test:
  secret_key_base: 774567030e120b58423fc2cba998c7acffa2a39c3d8a0355ee6d2630d1f8a780ab79f4babd0b48f3a461e2580047d44cdc595123fa601ec9320327ca1e3dfedc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
